service: database

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  tableName: ${self:custom.stage}-${file(../../serverless.common.yml):app-name}

provider:
  name: aws
  stage: dev
  region: ${file(../../serverless.common.yml):region}

resources:
  Resources:
    StorageTable:
      Type: AWS::DynamoDB::Table
      Properties:
        # Generate a name based on the stage
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: uploadId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: uploadId
            KeyType: RANGE
        # Set the capacity to auto-scale
        BillingMode: PAY_PER_REQUEST

  Outputs:
    StorageTableArn:
      Value:
         Fn::GetAtt:
          - StorageTable
          - Arn
      Export:
        Name: ${self:custom.stage}-${file(../../serverless.common.yml):app-name}-StorageTableArn
